server:
  rootPath: /api/v2
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

statusMessage: "working"

jerseyClient:
  timeout: 1m
  connectionRequestTimeout: 1m

nodeConfig:
    host: "localhost"
    port: 3000